# Generated by Django 4.0.3 on 2023-04-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_alter_hatmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatmodel',
            options={'ordering': ('fabric', 'style_name', 'color', 'url', 'location')},
        ),
    ]
